apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "laravel.fullname" . }}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduler
            image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
            volumeMounts:
            - name: env
              mountPath: /tmp/.env
              subPath: .env
            - name: php-ini-config
              mountPath: /usr/local/etc/php/php.ini
              subPath: php.ini
            command:
              - php
              - artisan
              - schedule:run
            {{- with .Values.app.extraEnv }}
            env:
              {{- toYaml . | nindent 12 }}
            {{- end }}
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - cp /tmp/.env /var/www/html/.env && cp -r /var/www/html/. /app && cd /var/www/html && sh deploy.sh
          restartPolicy: OnFailure